[background]
path = "/usr/share/backgrounds/greeter_background"
fit = "Contain"

[env]
ENV_VARIABLE = "value"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Adwaita"
cursor_blink = true
font_name = "Electrolize"
icon_theme_name = "Adwaita"
theme_name = "Adwaita-dark"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]

[appearance]
greeting_msg = "Welcome back!"

[widget.clock]
format = "%a %H:%M"
resolution = "500ms"
timezone = "America/Chicago"
label_width = 150
