add_newline = false
format = "$character"
right_format = """
$status\
$sudo\
$character\
$jobs\
$cmd_duration\
$conda\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmake\
$deno\
$golang\
$java\
$julia\
$python\
$rust\
$lua\
$username\
$hostname\
$directory"""
continuation_prompt = "[ 󰘍_ ](bg:bright-black cyan) "

[character]
format = "$symbol"
error_symbol = "[  ](bg:bright-black red)"
success_symbol = "[  ](bg:bright-black yellow)"
vimcmd_symbol = "[ : ](bg:bright-black bright-green)"
vimcmd_replace_one_symbol = "[ : ](bg:bright-black cyan)"
vimcmd_replace_symbol = "[ : ](bg:bright-black bright-cyan)"
vimcmd_visual_symbol = "[ : ](bg:bright-black blue)"

[cmake]
format = "[$symbol($version·)]($style)"
style = "bg:bright-black blue"
version_format = "${major}.${minor}"

[cmd_duration]
format = "[($duration·)]($style)"
min_time = 10_000
show_notifications = true
style = "bg:bright-black yellow"

[conda]
format = "[$symbol($environment·)]($style) "
style = "bg:bright-black bright-blue"
symbol = " "

[deno]
detect_extensions = ["js"]
detect_folders = ["js"]
format = "[$symbol($version·)]($style)"
style = "bg:bright-black bright-green"
symbol = " "
version_format = "${major}.${minor}"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
home_symbol = "󱂵 "
read_only = "󰉐 "
style = "bg:bright-black bright-cyan"
read_only_style = "bg:yellow blue"
truncation_length = 1
truncation_symbol = "… "
fish_style_pwd_dir_length = 1

[git_branch]
format = "[$symbol($branch·)]($style)"
style = "bg:bright-black purple"
symbol = ""

[git_commit]
format = "[($hash$tag)]($style)"
style = "bg:bright-black green"

[git_state]
format = "[$state($progress_current/$progress_total)]($style)"
style = "bg:bright-black bright-yellow"

[git_status]
format = "([$all_status$ahead_behind ]($style))"
style = "bg:bright-black red"

[golang]
format = "[$symbol($version·)]($style)"
style = "bg:bright-black bright-green"
symbol = " "
version_format = "${major}.${minor}"

[hostname]
format = "[$hostname]($style):"
style = "bg:bright-black bright-yellow"

[java]
format = "[$symbol($version·)]($style)"
style = "bg:bright-black bright-green"
symbol = " "
version_format = "${major}.${minor}"

[jobs]
format = "[$symbol$number]($style)"
style = "bg:bright-black bright-blue"
symbol = "󱀝 "

[julia]
format = "[$symbol($version·)]($style)"
style = "bg:bright-black bright-green"
symbol = " "
version_format = "${major}.${minor}"

[lua]
format = "[$symbol($version·)]($style)"
style = "bg:bright-black bright-green"
symbol = " "
version_format = "${major}.${minor}"

[python]
format = "[$symbol(\\($virtualenv\\))($version·)]($style)"
style = "bg:bright-black bright-green"
symbol = " "
version_format = "${major}.${minor}"

[rust]
format = "[$symbol($version·)]($style)"
style = "bg:bright-black bright-green"
symbol = " "
version_format = "${major}.${minor}"

[status]
disabled = false
format = "[ $status ]($style)"
style = "bg:red black"

[sudo]
disabled = false
format = "[ $symbol]($style)"
style = "bg:bright-black bright-green"
symbol = " "

[username]
format = "[($user·)]($style)"
style_root = "bg:bright-black red"
style_user = "bg:bright-black green"

[kotlin]
disabled = true
[kubernetes]
disabled = true
[line_break]
disabled = true
[aws]
disabled = true
[battery]
disabled = true
[crystal]
disabled = true
[dart]
disabled = true
[docker_context]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[env_var]
disabled = true
[erlang]
disabled = true
[gcloud]
disabled = true
[helm]
disabled = true
[hg_branch]
disabled = true
[memory_usage]
[nim]
disabled = true
[nix_shell]
disabled = true
[nodejs]
disabled = true
[ocaml]
disabled = true
[openstack]
disabled = true
[package]
disabled = true
[perl]
disabled = true
[php]
disabled = true
[purescript]
disabled = true
[red]
disabled = true
[rlang]
disabled = true
[ruby]
disabled = true
[scala]
disabled = true
[shell]
[shlvl]
[singularity]
disabled = true
[swift]
disabled = true
[terraform]
disabled = true
[time]
[vagrant]
disabled = true
[vlang]
disabled = true
[vcsh]
disabled = true
[zig]
disabled = true

